- name: "Accessories"
  description: "Accessories"
  critical: false
  hidden: false
  selected: false
  packages:
    - flameshot
- name: "Development"
  description: "Development"
  critical: false
  hidden: false
  selected: false
  packages:
    - code
    - kdevelop
- name: "Fonts"
  description: "Fonts"
  critical: false
  hidden: false
  selected: false
  packages:
    - terminus-font
- name: "Games"
  description: "Games"
  critical: false
  hidden: false
  selected: false
  packages:
    - arcolinux-meta-steam
    - lutris
- name: "Graphics"
  description: "Graphics"
  critical: false
  hidden: false
  selected: false
  packages:
    - blender
    - darktable
    - digikam
    - krita
    - pinta
- name: "Fun"
  description: "Fun"
  critical: false
  hidden: false
  selected: false
  packages:
    - arcolinux-meta-fun
- name: "Internet"
  description: "Internet"
  critical: false
  hidden: false
  selected: false
  packages:
    - brave
    - deluge
    - discord
    - dropbox
    - falkon
    - filezilla
    - firefox-i18n-$LOCALE
    - geary
    - hexchat
    - insync
    - ktorrent
    - opera
    - pidgin
    - qbittorrent
    - telegram-desktop
    - thunderbird
    - transmission-gtk
- name: "Libre Office Fresh"
  description: "Installs libre office fresh - feature branch - conflicts with still"
  critical: false
  hidden: false
  selected: false
  packages:
    - libreoffice-fresh
    - libreoffice-fresh-$LOCALE
    - hunspell-$LOCALE
- name: "Libre Office Still"
  description: "Installs libre office still - stable branch - conflicts with fresh"
  critical: false
  hidden: false
  selected: false
  packages:
    - libreoffice-still
    - libreoffice-still-$LOCALE
    - hunspell-$LOCALE
- name: "Multimedia"
  description: "Multimedia"
  critical: false
  hidden: false
  selected: false
  packages:
    - ardour
    - audacious
    - audacity
    - celluloid
    - clementine
    - deadbeef
    - elisa
    - handbrake
    - kdenlive
    - lollypop
    - lmms
    - obs-studio
    - openshot
    - mpv
    - rhythmbox
    - soundconverter
    - smplayer
    - spotify
    - spotifywm-git
- name: "Privacy"
  description: "Applications that ensure your privacy"
  critical: false
  hidden: false
  selected: false
  packages:
    - tor
    - privoxy
- name: "Themes"
  description: "Themes"
  critical: false
  hidden: false
  selected: false
  packages:
    - adapta-gtk-theme
    - arc-icon-theme
    - arcolinux-arc-kde
    - faba-icon-theme
    - moka-icon-theme
    - oxy-neon
    - paper-icon-theme
    - papirus-icon-theme
    - surfn-arc-breeze-icons-git
    - xcursor-simpleandsoft
- name: "Utilities"
  description: "Utilities"
  critical: false
  hidden: false
  selected: false
  packages:
    - gitahead-bin
    - gitfiend
    - glances
    - gtop
    - powertop
    - systemd-manager
- name: "Virtualbox for Linux kernel"
  description: "Installs virtualbox for linux kernel"
  critical: false
  hidden: false
  selected: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-headers
- name: "Virtualbox for Linux-lts kernel"
  description: "Installs virtualbox for linux-lts kernel"
  critical: false
  hidden: false
  selected: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-lts-headers
    - linux-lts
- name: "WPS Office"
  description: "Installs wps office"
  critical: false
  hidden: false
  selected: false
  packages:
    - wps-office
    - wps-office-mime
    - ttf-wps-fonts
